Test converstion

diff --git a/.github/workflows/aws_deploy.yaml b/.github/workflows/aws_deploy.yaml
--- a/.github/workflows/aws_deploy.yaml
+++ b/.github/workflows/aws_deploy.yaml
@@ -141,14 +141,22 @@ jobs:
         cat ${{ github.WORKSPACE }}/AWS_infra/terraform.tfstate.d/${{ inputs.environment }}/terraform.tfstate | jq -r .outputs.rsa_private_key.value > ${{ env.CALDERA_KEY }}
         echo la SHA en fichero
         cat ${{ env.CALDERA_KEY }}
-        chmod 400 ${{ env.CALDERA_KEY }}
+        chmod 600 ${{ env.CALDERA_KEY }}
+    - name: Test ssh
+      run: |
+        mkdir -p ~/.ssh
+        ssh-keygen -p -N "" -f ${{ env.CALDERA_KEY }}
+        cp ${{ env.CALDERA_KEY }} > ~/.ssh/id_rsa
+        chmod 600 ~/.ssh/id_rsa
+        ssh-keygen -y -f ${{ env.CALDERA_KEY }} > ~/.ssh/id_rsa.pub
+        chmod 644 ~/.ssh/id_rsa.pub
     - name: Deploy Mitre Caldera
       run: |
         cd ${{ env.ANSIBLE_DATA_DIR }}
         ls -lah ${{ env.CALDERA_KEY }}
         cat ${{ env.CALDERA_KEY }}
         export ANSIBLE_HOST_KEY_CHECKING=false
-        ansible-playbook -i ${{ env.ANSIBLE_HOST }} --private-key ${{ env.CALDERA_KEY }} install-caldera-server.yml
+        ansible-playbook -i ${{ env.ANSIBLE_HOST }} install-caldera-server.yml
 
   wait-caldera-server:
     runs-on: ubuntu-20.04
@@ -220,3 +228,14 @@ jobs:
         git add -f AWS_infra/terraform.tfs* || true
         git commit -m "Autometed push terraform tfstate from ${{ github.GITHUB_EVENT_NAME }}" || true
         git push
+
+#  pruebas-openssh:
+#    runs-on: ubuntu-20.04
+#    needs: [deploy-caldera-server,deploy-caldera-hosts]
+#    steps:
+#      - name: Transformar-openssh
+#        run: |
+#          ssh-keygen -p -N "" -f /path/to/key
+#          echo $SERVER_IP
+#          while ! curl -H "KEY:redAPIKeySantander22" http://$SERVER_IP:2288/api/v2/agents &>/dev/null; do echo "Curl Fail - `date`" && sleep 1; done
+
