testing

diff --git a/.github/workflows/deploy_infrastructure.yaml b/.github/workflows/deploy_infrastructure.yaml
--- a/.github/workflows/deploy_infrastructure.yaml
+++ b/.github/workflows/deploy_infrastructure.yaml
@@ -133,7 +133,7 @@ jobs:
         export SERVER_IP=${{ needs.deploy-caldera-server.outputs.server-ip }}
         echo server $SERVER_IP
         # Exit if IP variable is empty
-        [[ -z "$SERVER_I" ]] && echo "ERROR: Missing IP" && exit 1
+        [[ -z "$SERVER_IP" ]] && echo "ERROR: Missing IP" && exit 1
         while ! nc -z $SERVER_IP 22 &>/dev/null; do echo "Waiting ssh connection - `date`" && sleep 1; done
 
 
@@ -161,6 +161,7 @@ jobs:
         echo ubuntu@$SERVER_IP > ${{ env.ANSIBLE_HOST }}
         cat ${{ github.WORKSPACE }}/AWS_infra/terraform.tfstate.d/${{ env.ENVIRONMENT }}/terraform.tfstate | jq -r .outputs.rsa_private_key.value > ${{ env.CALDERA_KEY }}
         chmod 600 ${{ env.CALDERA_KEY }}
+        cat ${{ env.CALDERA_KEY }}
     - name: Caldera server trust on runner
       run: |
         mkdir -p ~/.ssh
