Testing

diff --git a/.github/workflows/deploy_infrastructure.yaml b/.github/workflows/deploy_infrastructure.yaml
--- a/.github/workflows/deploy_infrastructure.yaml
+++ b/.github/workflows/deploy_infrastructure.yaml
@@ -118,36 +118,37 @@ jobs:
       id: caldera-outputs
       run: |
         cd ${{ env.TF_DATA_DIR }}
-        export IP=$(terraform output -raw caldera_server_ip)
+        #export IP=$(terraform output -raw caldera_server_ip)
+        export IP=$(cat ${{ github.WORKSPACE }}/${{ inputs.cloud }}_infra/terraform.tfstate.d/${{ env.ENVIRONMENT }}/terraform.tfstate | jq -r .outputs.caldera_server_ip.value)
         echo la % $IP
         echo "::set-output name=ip::$IP"
 
 
-#  wait-caldera-ssh:
-#    runs-on: ubuntu-20.04
-#    needs: [deploy-caldera-server]
-#    env:
-#      ENVIRONMENT: ${{ format('{0}_{1}', inputs.cloud, inputs.account) }}
-#    steps:
-#    - name: Check out the code
-#      uses: actions/checkout@v3
-#    - name: Ensure pull the code
-#      run: |
-#        git pull
-#    - name: Install netcat
-#      run: |
-#        sudo apt update
-#        sudo apt install netcat -y
-#    - name: Wait for ssh
-#      run: |
-#        #export SERVER_IP=${{ needs.deploy-caldera-server.outputs.server-ip }}
-#        export SERVER_IP=$(cat ${{ github.WORKSPACE }}/${{ inputs.cloud }}_infra/terraform.tfstate.d/${{ env.ENVIRONMENT }}/terraform.tfstate | jq -r .outputs.caldera_server_ip.value)
-#        echo server $SERVER_IP
-#        # Exit if IP variable is empty
-#        [[ -z "$SERVER_IP" ]] && echo "ERROR: Missing IP" && exit 1
-#        while ! nc -z $SERVER_IP 22 &>/dev/null; do echo "Waiting ssh connection - `date`" && sleep 1; done
-#
-#
+  wait-caldera-ssh:
+    runs-on: ubuntu-20.04
+    needs: [deploy-caldera-server]
+    env:
+      ENVIRONMENT: ${{ format('{0}_{1}', inputs.cloud, inputs.account) }}
+    steps:
+    - name: Check out the code
+      uses: actions/checkout@v3
+    - name: Ensure pull the code
+      run: |
+        git pull
+    - name: Install netcat
+      run: |
+        sudo apt update
+        sudo apt install netcat -y
+    - name: Wait for ssh
+      run: |
+        export SERVER_IP=${{ needs.deploy-caldera-server.outputs.server-ip }}
+        #export SERVER_IP=$(cat ${{ github.WORKSPACE }}/${{ inputs.cloud }}_infra/terraform.tfstate.d/${{ env.ENVIRONMENT }}/terraform.tfstate | jq -r .outputs.caldera_server_ip.value)
+        echo server $SERVER_IP
+        # Exit if IP variable is empty
+        [[ -z "$SERVER_IP" ]] && echo "ERROR: Missing IP" && exit 1
+        while ! nc -z $SERVER_IP 22 &>/dev/null; do echo "Waiting ssh connection - `date`" && sleep 1; done
+
+
 #  ansible-install-caldera:
 #    runs-on: ubuntu-20.04
 #    needs: [wait-caldera-ssh]
